{% set version = "0.0-86.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gwidgetsrgtk2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gWidgetsRGtk2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gWidgetsRGtk2/gWidgetsRGtk2_{{ version }}.tar.gz
  sha256: 56687a718b159011ef5cdaefa5ccccdfc977014b08a423cf1280a0bf55e221c0

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rgtk2
    - r-cairodevice
    - r-gwidgets
  run:
    - r-base
    - r-rgtk2
    - r-cairodevice
    - r-gwidgets

test:
  commands:
    - xvfb-run -a bash -c "$R -e \"library('cairoDevice')\""  # [linux]
    - $R -e "library('cairoDevice')"             # [osx]
    - "\"%R%\" -e \"library('gWidgetsRGtk2')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gWidgetsRGtk2
  license: GPL (>= 2)
  summary: Port of the gWidgets API to the RGtk2 toolkit.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: gWidgetsRGtk2
# Version: 0.0-86
# Title: Toolkit Implementation of gWidgets for RGtk2
# Author: Michael Lawrence, John Verzani
# Maintainer: John Verzani <jverzani@gmail.com>
# Depends: methods, grDevices, utils, graphics, RGtk2, gWidgets, cairoDevice
# Enhances: RGtk2Extras
# Description: Port of the gWidgets API to the RGtk2 toolkit.
# License: GPL (>= 2)
# LazyLoad: yes
# Packaged: 2018-01-29 17:10:41 UTC; parallels
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2018-03-01 17:38:49 UTC
# RoxygenNote: 6.0.1
