travis:
  secure:
    BINSTAR_TOKEN: GB1FcxaqkFVIUS+igFBcCp/Fgj/49MNozCgv0dxR4Q1aw8U+pnDJcMxECqwfV4w07FrccUcCALuSlMN24eLH9czaE0A3rK3Nw6DMnF7fT1sge7oVBxqOZSUbkrmMJhUKw3mZK6cMm+vWZd5SuW5TBnDOVSGaDK2oCbmf1TlGfYw/4RP9wjo1rQXyga0FZ7Eg0HKTn8TtKyhAd6eyHKsvW45bpwVx4Fi8kl9v9Oga3PHErQ6nqieMByrJEk+mQnu2e9diWvzcoPL2Dk1Wsy8NfHcf1CVKQcEAPzMfeqzuq0puVx36OE84FQndxtBCvnKqHEaiDkJN4kEumP5Cd+ohvC1vrkr60AU4Lj42Bz8hEPkGwg0kXv8I0cjuRPofOmXRV1Z08/QhfsC8Bidrc4ysvNT3/TpAKtw9x7JfqKY+KUREFevK2yjn2Fg2YPAmhJrEOaogSIzY9pMPufOcqYmUBc2E/jurnGkdH7qa+oZa0lkjMMyBWy55qb92mp80f0lDZEuFjZt+oSk5b4OPjnHswvgYr/VliFoqqlUBqhYgED6YriRbNgmdzXKH0FehVIsPSk54Txj8JDu93lnnQ7tZXfA7YZPH6heFwEqRYBrjb2kYTz4Jj1mtkZ62nvwf0Y4OjPDjDYSx6YhR3rB32YDFaBhrkqZdLftPe8FCfiEnufU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
